--=======================================================================================================>
-- in this case, AdditionalProperty is the delay between each check

-- EnumName, EnumValue, AdditionalProperty
return {
	--======================================================================>
	{"Automatic",   1},
	{"VoxelBoxRegion", 2},
	{"VoxelBoxRaycast",  3},
	{"ExactBoxRegion", 4},
	{"ExactBoxRaycast",  5},
	{"PerPartRegion", 6},
	{"PerPartInsidePart", 7},
	{"PerPartRaycast", 8},
	--======================================================================>
}



-- If All the Parts of the Zones are non complex box parts
-- Use Regions

--=======================================================================================================>